rules:
    php.object_parameter_not_type_hinted:
        enabled: false # deliberate to squeeze out more performance, however slight
    php.bad_mutator_method_name_for_boolean_property:
        enabled: false # code style disagreement
    php.interface_has_no_interface_suffix:
        enabled: false # code style disagreement
