language: php
matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: nightly
      env: PHP_CS_FIXER_IGNORE_ENV=1
  fast_finish: true
  allow_failures:
    - php: nightly
before_install: phpenv config-rm xdebug.ini || true
install: make vendor
script: make ci
after_script: bash <(curl -s https://codecov.io/bash)
